### ISSUE TITLE
Invalid output length for certain values

### ISSUE THREAD

**Issue by violog** [vivianjeng/poseidon-online#1]
I can try providing the input in hex:
`0x5fe7f977e71dba2ea1a68e21057beebb9be2ac30c6410aa38d4f3fbe41dcffd2`

The result would be
`0xa10840c3254a1ef449d08d46950c077a2e18fc004a812ca306b6caf3f7edb1`
which has a 1 missing byte (0x was added by myself).

How a non-fixed length could appear? Never saw it in MD5, SHA, Keccak, RIPEMD160. I am pretty new to Poseidon and trying to figure out whether it's a bug or a feature.

**Comment by vivianjeng** [comment]
hi @violog 
I don't pad the hash with 0s
so it might be missing bytes

**Comment by violog** [comment]
Hi @vivianjeng, thanks for your feedback. I think you close it then, unless you're uncertain about the cause.
